# Generated by Django 4.0.6 on 2022-07-23 16:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0003_rename_age_person_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('BidId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Ammount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bRating', models.FloatField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sRating', models.FloatField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('BidderIds', models.ManyToManyField(through='api.Bid', to='api.bidder')),
                ('SellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
                ('categoryIds', models.ManyToManyField(to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='BidderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bidder'),
        ),
        migrations.AddField(
            model_name='bid',
            name='ItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
